name: Build & upload new version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup environment
        shell: bash
        run: |
          python -m pip install -r requirements.txt
          python setup.py setup --global
      - name: Build
        run: python setup.py build --global
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: dist files
          path: dist/discord.fm-*
